import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ludo Board',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Ludo Board'),
        ),
        body: Center(
          child: Container(
            width: 379,
            height: 379,
            decoration: BoxDecoration(boxShadow: [
              BoxShadow(
                color: Colors.grey.withOpacity(0.5),
                spreadRadius: 5,
                blurRadius: 9,
                offset: const Offset(0, 3), // changes position of shadow
              ),
            ], border: Border.all(color: Colors.black, width: 2)),
            child: Column(
              children: [
                Row(
                  children: [
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.white),
                    boxes(Colors.greenAccent),
                    boxes(Colors.greenAccent),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.white),
                    boxes(Colors.greenAccent),
                    boxes(Colors.white),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.white),
                    boxes(Colors.greenAccent),
                    boxes(Colors.white),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.white),
                    boxes(Colors.greenAccent),
                    boxes(Colors.white),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.red),
                    boxes(Colors.white),
                    boxes(Colors.greenAccent),
                    boxes(Colors.white),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                    boxes(Colors.green),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.white),
                    boxes(Colors.redAccent),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    Container(
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [Colors.green, Colors.red],
                          begin: Alignment.topRight,
                          end: Alignment.bottomLeft,
                        ),
                        border: Border.all(width: 0.2),
                      ),
                      height: 25,
                      width: 25,
                    ),
                    boxes(Colors.green),
                    Container(
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [Colors.green, Colors.yellow],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        ),
                        border: Border.all(width: 0.2),
                      ),
                      height: 25,
                      width: 25,
                    ),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.white),
                    boxes(Colors.redAccent),
                    boxes(Colors.redAccent),
                    boxes(Colors.redAccent),
                    boxes(Colors.redAccent),
                    boxes(Colors.redAccent),
                    boxes(Colors.red),
                    boxes(Colors.white),
                    boxes(Colors.yellow),
                    boxes(Colors.yellowAccent),
                    boxes(Colors.yellowAccent),
                    boxes(Colors.yellowAccent),
                    boxes(Colors.yellowAccent),
                    boxes(Colors.yellowAccent),
                    boxes(Colors.white),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    Container(
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [Colors.red, Colors.blue],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        ),
                        border: Border.all(width: 0.2),
                      ),
                      height: 25,
                      width: 25,
                    ),
                    boxes(Colors.blue),
                    Container(
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [Colors.yellow, Colors.blue],
                          begin: Alignment.topRight,
                          end: Alignment.bottomLeft,
                        ),
                        border: Border.all(width: 0.2),
                      ),
                      height: 25,
                      width: 25,
                    ),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.yellowAccent),
                    boxes(Colors.white),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.white),
                    boxes(Colors.blueAccent),
                    boxes(Colors.white),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.white),
                    boxes(Colors.blueAccent),
                    boxes(Colors.white),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.white),
                    boxes(Colors.blueAccent),
                    boxes(Colors.white),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.white),
                    boxes(Colors.blueAccent),
                    boxes(Colors.white),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blueAccent),
                    boxes(Colors.blueAccent),
                    boxes(Colors.white),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                  ],
                ),
                Row(
                  children: [
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.blue),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.white),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                    boxes(Colors.yellow),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget boxes(Color color) {
    return Container(
      decoration: BoxDecoration(
        color: color,
        border: Border.all(width: 0.2),
      ),
      height: 25,
      width: 25,
    );
  }
}
